<a href="https://colab.research.google.com/github/sowmyarshetty/NNClass/blob/main/build_a_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import requests
import pickle
import io

# Import the preprocessed data
X_preprocessed_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/preprocessed_fungi.pkl"
y_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/fungi_y.pkl"

X = pickle.load(io.BytesIO(requests.get(X_preprocessed_url).content))
y = pickle.load(io.BytesIO(requests.get(y_url).content))

print(X[0])
print(y.head())


[[[0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.54901963 0.5568628  0.5529412 ]
  [0.54901963 0.5568628  0.5529412 ]
  [0.5529412  0.56078434 0.5568628 ]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.53333336 0.5411765  0.5372549 ]
  [0.5411765  0.54901963 0.54509807]
  [0.54901963 0.5568628  0.5529412 ]
  ...
  [0.5254902  0.5411765  0.5372549 ]
  [0.5294118  0.54509807 0.5411765 ]
  [0.5294118  0.54509807 0.5411765 ]]

 ...

 [[0.5529412  0.53333336 0.4509804 ]
  [0.5529412  0.53333336 0.4509804 ]
  [0.54901963 0.5254902  0.44705883]
  ...
  [0.54509807 0.5529412  0.5568628 ]
  [0.54509807 0.5529412  0.56078434]
  [0.54509807 0.5529412  0.56078434]]

 [[0.54901963 0.5254902  0.44705883]
  [0.54901963 0.5254902  0.44705883]


In [10]:
X.shape

(250, 250, 250, 3)

In [9]:
# Label encode the y data
y_encoder = LabelEncoder().fit(y)
y = y_encoder.transform(y)

# Convert values to numpy arrays
X = np.array(X)

# Split the training dataset into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define a CNN model; make sure to use the correct values for input shape!
# HINT: Check the preprocessing activity to see the dimensions we used.

#X.shape

# Compile the model


model = keras.Sequential([
    #2D convolutional layer
    layers.Conv2D(32,(3,3),activation = "relu",input_shape=(250,250,3 ),name="convulation"),
    #max pooling layer
    layers.MaxPooling2D((2,2)),
    #flatten layer
    layers.Flatten(name = "flatten"),
    #classification
    layers.Dense(64,activation="relu",name="dense"),
    #output layer - the number 1 signifies ( binary but 1 class, 2 - multi class classificaiton)
   layers.Dense(2,activation ="sigmoid",name="output")
])



# Train the model
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ convulation (Conv2D)                 │ (None, 248, 248, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 124, 124, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 492032)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │      31,490,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ output (Dense)                       │ (None, 2)                   │             130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31,491,138 (120.13 MB)

 Trainable params: 31,491,138 (120.13 MB)

 Non-trainable params: 0 (0.00 B)

In [11]:

# Compile the model
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

# Train the model
epochs = 2
batch_size = 32
history = model.fit(X_train,y_train,epochs=epochs,batch_size=batch_size,validation_data=(X_test,y_test))




Epoch 1/2
7/7 ━━━━━━━━━━━━━━━━━━━━ 17s 2s/step - accuracy: 0.5637 - loss: 16.1732 - val_accuracy: 0.3000 - val_loss: 8.2659
Epoch 2/2
7/7 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step - accuracy: 0.4464 - loss: 3.6353 - val_accuracy: 0.7000 - val_loss: 0.6906
